* TODO shorucut
  Show/Hide:~
    <TAB>           - Cycle Visibility

  Editing Structure:~
      <S-CR>          - insert heading below, taking over children
      m}              - move heading down
      m{              - move heading up
      m]]             - move subtree down
      m[[             - move subtree up

      yah             - yank heading
      dah             - delete heading
      yar             - yank subtree
      dar             - delete subtree
      p               - paste subtree

      >> or >ah       - demote heading
      << or <ah       - promote heading
      >ar             - demote subtree
      <ar             - promote subtree

  Hyperlinks:~
    gl              - goto link
    gyl             - yank link
    gil             - insert new link


** heading
	- `*`로 시작
	- (normal-mode)>>, << 로 깊이제


** 목록에대해
	- 순서있는 목록
		1. or 1)
		1)

	- 순서없는 목록
		+, -로 시작
순서 없는 목록은 -, + 또는 \*로 시작합니다. 순서 있는 목록은 숫자와 점으로 시작합니다. 설명은 ::이 붙습니다.


** 마크업
단어에 *굵게*, /기울임꼴/, _밑줄_, =코드=, ~요약~ 등의 마크업을 쓸 수 있다. 꼭 필요한 경우 +삭제선+도 가능하다.

** todo 항목제어
	- <S-left/right> :: DONE/TODO 등의변경
	- ??:: 할일목록보기
	- 설정으로 추가해야함 ::
		#+TODO: TODO IN-PROGRESS WAITING DONE
	20. ii
	[@20] ww
 21. jj
** agenda(완료해야할것)
*
*
*
*
* a														   :wefwef:wefknkenf:

*<2018-07-15 Sun>
[2018-07-15 Sun]

*
* editing
************ toggle folding: <tab>/<s-tab>
* heading

* Top level heading
** Second level
*** 3rd level
	some text
*** 3rd level
	more text

- heading-moving
  }                     Next heading.

  {                     Previous heading.

  ]]                    Next heading same level.

  [[                    Previous heading same level.

  g{                    Backward to higher level heading.

  g}                    Forward to higher level heading.

- text-objects motion??
ih ah

-


* TODO
1. indent
  Some people find the many stars too noisy and would prefer an outline
  that has whitespace followed by a single star as headline starters.
  |g:org_heading_shade_leading_stars| describes a setup to realize this.

  Body text under headings is not indented by default, but you can control
  this  with the  |g:org_indent| variable.
2.

* nnnnn
*
