version: '3'
services:
  node:
    image: elfmagic86/angular1blog:v1
    container_name: angular1blog
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    links:
      - mongo
    command: ["npm", "start"]
  mongo:
    image: mongo:latest
    expose:
      - 27017

