
# build
# https://nodejs.org/ko/docs/guides/nodejs-docker-webapp/

FROM node:boron

# 앱 디렉토리 생성
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# 앱 의존성 설치
COPY package.json /usr/src/app/
RUN npm install

# 앱 소스 추가
COPY . /usr/src/app

# docker-compose에서 정의
# EXPOSE 3000
# entrypoint
# CMD [ "npm", "start" ]

